AWSTemplateFormatVersion: '2010-09-09'
Description: Secret Manager with generated password

Parameters:
  environment:
    Type: String
  product:
    Type: String
  service:
    Type: String
Resources:
  dbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${environment}/${product}/db/creds"
      GenerateSecretString:
        SecretStringTemplate: '{"username":"admin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

Outputs:
  SecretArn:
    Value: !Ref dbSecret